VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "i_C_SETTINGS_Item"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Package: SETTINGS (allowing to work with a settings sheet)
'============================================================================================
' Purpose: data fields of setting sheet entries
' 0.2.0    26.10.2023    gueleh    Imported from FF2 and renamed
Option Explicit

Public sID As String
Public sName As String
Public sValue As String
Public sFormulaLocal As String


